name: CI

on:
  pull_request:
    branches:
      - main

#fsdsd
jobs:
  run-ci-template:
    uses: douglasmendeslda/ci-template/.github/workflows/ci-template.yml@main
    with:
      python-version: '3.9'
